version: '3.5'

services:
    web:
        image: jorgevargasjvm/docker-compose-practica:v1.0.0
        container_name: PracticaDockerCompose
        depends_on:
            - mysql
        ports:
            - "80:8080"
        environment:
            DB_HOST: mysql
            DB_DATABASE: practicaDockerComposeDB
            DB_USER: root
            DB_PASSWORD: root
            DB_PORT: 33006

    mysql:
        image : mysql:5.7
        restart: always
        ports:
            - "33006:3306"
        volumes:
            - ./data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: practicaDockerComposeDB
